[package]
name = "slatehub"
version = "0.1.0"
edition = "2024"
publish = false
authors = ["Chris Bruce <chris@secedastudios.com>"]
license = "Apache-2.0"

[dependencies]
axum = "0.8.4"
chrono = "0.4"
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
surrealdb = "2.3.7"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["full"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["trace", "cors", "fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "fmt",
    "json",
] }
